version: 2
project_name: asyncjobs

release:
  github:
    owner: choria-io
    name: asyncjobs
  name_template: "Release {{.Version}}"
  draft: true

builds:
  - main: ./ajc
    id: ajc
    binary: ajc
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm

archives:
  - name_template: "asyncjobs-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - registry.choria.io/choria/ccm
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Choria Configuration Manager"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

    platforms:
      - linux/amd64
      - linux/arm64

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

nfpms:
  - file_name_template: 'asyncjobs-{{.Version}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    homepage:  https://github.com/choria-io/asyncjobs
    description: Choria Asynchronous Jobs CLI
    maintainer: R.I. Pienaar <rip@devco.net>
    license: Apache 2.0
    vendor: Choria
    formats:
      - deb
      - rpm
