baseURL = "https://choria-io.github.io/asyncjobs/"
languageCode = "en-us"
title = "Choria Async Jobs Documentation"
theme = "hugo-theme-relearn"
canonifyURLs = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
author = "Choria Project"
showVisitedLinks = false
disableLanguageSwitchingButton = true
themeVariant = "asyncjobs"
disableInlineCopyToClipBoard = true
alwaysopen = true

[markup]
  [markup.highlight]
    # if set to `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT mermaid code fences will not work anymore! So this is a mandatory
    # setting for your site
    guessSyntax = false
    style = "tango"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/choria-io/asyncjobs"
weight = 10

[[menu.shortcuts]]
name = "<i class='far fa-save'></i> Download"
url = "https://github.com/choria-io/asyncjobs/releases"
weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-comments'></i> Discussions"
url = "https://github.com/choria-io/asyncjobs/discussions"
weight = 12

[[menu.shortcuts]]
name = "<i class='far fa-life-ring'></i> Issues"
url = "https://github.com/choria-io/asyncjobs/issues"
weight = 13

[[menu.shortcuts]]
name = "<i class='fab fa-slack'></i> #choria"
url = "https://slack.puppet.com/"
weight = 14
